FROM homeassistant/home-assistant:stable

RUN python3 -m pip install "green-energy==0.1.0"

COPY custom_components/green_energy /config/custom_components/green_energy
COPY configuration.dev.yaml /config/configuration.yaml